# ~/.config/helix/themes/aura.toml
theme = "aura"
[editor]
auto-completion = true
path-completion = true
continue-comments = false
completion-replace = true
trim-trailing-whitespace = true
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
